### ISSUE TITLE
Running the control fails, displaying "The type 'IHandle<>' is defined in an assembly that is not referenced"

### ISSUE THREAD

**Issue by Nora-Zhou01** [dotnet/winforms#10661]
### .NET version

9.0.100-alpha.1.24062.11

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes

### Issue description

Running the control fails, displaying "The type 'IHandle<>' is defined in an assembly that is not referenced."
In the latest .Net 9.0 SDK build: 9.0.100-alpha.1.24062.11, an exception pops up:

_The type 'IHandle<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.Windows.Core, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'._

https://github.com/dotnet/winforms/assets/104609169/32139b56-6fa1-4bfa-800d-0b30407e9ca5

### Steps to reproduce

1. Create a Winforms .Net application
2. Add a NumericUpDown control to form designer
3. Build and run application

**More info:**

1. There is a **workaround**: manually add "**System.Private.Windows.Core.dll**" to the project. The project can run normally
2. This issue occurs in the following controls: NumericUpDown, TrackBar, Process, DataGridView, PictureBox, SplitContainer

**Comment by JeremyKuhne** [comment]
Hmm. Happens when you cast any control to any interface, but not when you cast to base classes. Not what I would have expected.

@jaredpar do you know why casting to a public interface needs an explicit reference to an assembly where an internal interface is defined? Is this expected?

```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	CS0012	The type 'IHandle<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.Windows.Core, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.	WinFormsApp5	C:\Users\jkuhne\source\repos\WinFormsApp5\WinFormsApp5\Form1.Designer.cs	32	N/A	
```

**Comment by jaredpar** [comment]
> do you know why casting to a public interface needs an explicit reference to an assembly where an internal interface is defined?

If the `public` interface implements the `internal` interface then it's possible the compiler may pull on that when trying to resolve the symbols. 

> Is this expected?

In general if you perform compilations where you do not give the compiler the full reference graph you are playing with fire. While the compiler is careful to not traverse symbols unless it needs to it is sometimes necessary. Bug fixes, new features, etc ... can always force us to look a bit deeper on existing symbols and thus pull in more assembly references. This can break existing code which only gave the compiler a partial reference graph. Such behavior changes are considered "by design" / "won't fix" bugs though. If we could go back in time and fail compilations that didn't provide full reference graphs we'd strongly consider doing so to avoid issues like this.

**Comment by elachlan** [comment]
Fixed by #10673

**Comment by MandiMan** [comment]
Verified on .NET 9.0.100-alpha.1.24068.28 + latest dlls from Winforms Repo of main branch, **it is not fixed**. Running the control still fails, displaying "The type 'IHandle<>' is defined in an assembly that is not referenced."

https://github.com/dotnet/winforms/assets/108860782/5ea6d078-49c8-4d86-838d-0ed68092a4c8

**Comment by JeremyKuhne** [comment]
@MandiMan 24069 is the first SDK build to include the fix

**Comment by MandiMan** [comment]
Verified this on .NET 9.0.100-alpha.1.24070.3, issue was fixed. Running the control was successful.

https://github.com/dotnet/winforms/assets/108860782/4f985c86-31d8-48bc-a63b-b1b45c0b45e4
