### ISSUE TITLE
Control.Enabled not virtual

### ISSUE THREAD

**Issue by trivalik** [dotnet/winforms#1147]
* .NET Core Version: only winforms related
* Have you experienced this same bug with .NET Framework?: Yes

**Problem description:**
We integrated a internal system to change independent from control the enable flag, therefore we add the Enabled property to hide the original function. Make "Enabled" virtual would solve our issue that if it casted down to "Control" the wrong "Enabled" property is called. With OnEnabledChanged event could we not get our internal system to work. Maybe is this for other properties also useful to do this virtual.

**Actual behavior:**
```C#
var someControl = new ControlX();
(someControl as Control).Enabled; --> calls the Control.Enabled
```
**Expected behavior:**
```C#
var someControl = new ControlX();
(someControl as Control).Enabled; --> calls the ControlX.Enabled
```
**Minimal repro:**
```C#
var someControl = new ControlX();
(someControl as Control).Enabled;
```

**Comment by weltkante** [comment]
I think overriding Control.Enabled and returning anything else than the base class value would just by a lie (i.e. would not lead to changing control state), since the implementation is in the setter. So the getter cannot be virtual, only the setter.

**Comment by merriemcgaw** [comment]
We are hesitant to make a change like this, because it has been working this way and there are expectations for how this will behave. If we get more feedback wanting a change like this I'm happy to revisit the issue.

**Comment by trivalik** [comment]
Sorry there was a misunderstanding, it is of course just the setter implementation, which is changed.

**Comment by weltkante** [comment]
> or do it like for the Visible property a virtual SetVisibleCore function is used

Yes, that is more or less what I meant when saying making the setter virtual. Since you cannot make just the the setter of a property virtual in C# having a separate virtual function being called by the setter is the only workable implementation.

**Comment by trivalik** [comment]
I implemented an example https://github.com/trivalik/winforms/tree/OverrideSetEnabled, which means that derived control could exchange enable behavior by several factors

**Comment by weltkante** [comment]
@trivalik You forgot to make it virtual ;)

Also your logic forgets to update `value` so the subsequent code will use outdated data to compute focus.

**Comment by trivalik** [comment]
Thanks, for your review. I had no .NET 6 to check. I fixed your concerns.
