### ISSUE TITLE
`ListView.IndexOfKey()` returns incorrect value

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/winforms#2867]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/887266/problema-com-listview.html)._

---
Bom dia á todos, o que ocorre é o seguinte, quando inserimos um controle **ListView em um Form VB**, acontece que eu declaro em **Design as colunas deste ListView e sempre coloco na propriedade (Name) das colunas** um nome realtivo á esta coluna, até aí tudo bem em _Design_!

Mas o problema suge no momento em **Execução**, sendo que em execução todas as propriedades (Name) das colunas se torna uma **string vazia**, então o que acontece acredito seja um problema no VB, pois em **Design o mesmo mantém os campos das colunas da ListView (Name)** só que em execução perdemos estes campos!

Então fiz o teste de adicionar na programação todos os campos das colunas (Name) e os mesmos colocando na programação se mantém em todo o processo da execução, então vejo que o problema é manter o mesmo que foi feito em Design também em execução!

Espero que tenham compreendido a minha explicação e que isso realmente seja um porblema que possa ser corrigido em uma atualização futura!

Grato,
Renato

---
#### Visual Studio Feedback System on 1/17/2020, 07:42 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Zheng Li [MSFT] on 1/19/2020, 10:15 AM: 

<p>Dear customer, thanks for your feedback.</p>
<p>I can’t repoduce the issue accordind to ypur description, Please see the reproduce  gif, and figure out if there have wrong steps. And could you please provide more info for us to investigate the issue in the future, such as your reproduce Video, or reproduce gif.</p>
<p>In addtion, have you have the same experience in before, such VS 16.2, VS 2017. And if the issue also can reproduce on C# Windows Form Application.</p>
<p>Repro Gif:</p><p><img src="https://developercommunity.visualstudio.com/storage/temp/114635-feedback.gif">Thanks</p><p>
Zheng</p>

#### Renato Maia on 1/23/2020, 00:52 AM: 

See that the program is running without change and with its column names declared in the control, but as soon as it is executed, it no longer has this information! So I put the name of the columns in code and it doesn&#39;t lose in execution!
#### Renato Maia on 1/21/2020, 07:16 PM: 

Good morning my friend, thanks for the feedback you gave and the work you had in making a GIF of the procedure, well what I can say you did correctly what is happening, but the problem is generated when the application is running , because when running these Listview columns (Name) are completely reset (string.empty), that is, you don&#39;t have any more information about them running, so you must insert them again in code, so the system keeps these columns (Name) in Listview! So I can use the columns .IndexOfKey, because I believe that you remember more (name) than Interger to return it!<br><br>* I using Google Translate for creat this text!
#### Zheng Li [MSFT] on 1/22/2020, 11:00 AM: 

<p>Dear customer, thankk for your response.</p>
<p>For the issue, could you please provide more details for use? such as your repro reproduce steps/Gif/Video etc.</p>
<p>There have some confused that about the “The issue generated when application is runing”,what’s meaning? it’s that calling the columns(Name) in running? how to implement it?</p>
<p>Will be appreciate if you also can provide your project for us to investigate the issuein future?</p>
<p>Thanks<br>
Zheng</p>

#### Zheng Li [MSFT] on 2/5/2020, 04:25 PM: 

<p>Thanks for your response, Ciould you please provide reproduce steps &amp; project for us tp investigate the issue in tthe future.</p>
<p>Thanks<br>
Zheng</p>

#### Visual Studio Feedback System on 2/12/2020, 08:17 PM: 

We will close this report in 14 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.
#### Renato Maia on 2/13/2020, 00:53 AM: 

Hi friend, i send details of problem to user Zheng Li, no have more details with me! I send the video of project and see the problem!
#### Zheng Li [MSFT] on 2/17/2020, 02:29 PM: 

<p>Dear customer, thanks for your help and details info.</p>
<p>For the issue, we found the root cause is that Docs say that ColumnHeaderCollection.IndexOfKey uses <a target='_blank' href="http://ColumnHeader.Name">ColumnHeader.Name</a> property as the key. However designer does not generate ‘<a target='_blank' href="http://columnHeader1.Name">columnHeader1.Name</a> =”columnHeader1”; line in InitializeComponent in designer.cs. As a result, runtime does not have this value and uses an empty string as a key in the columns collection.</p>
<p>And we provide the workaround for now, please refer it, and we are investigate it for now, will give you a response once have ny process.</p>
<p><strong>Workaround</strong><br>
So when I do this:<br>
public Form1()<br>
{<br>
InitializeComponent();<br>
<a target='_blank' href="http://columnHeader1.Name">columnHeader1.Name</a> = “columnHeader1”;<br>
<a target='_blank' href="http://columnHeader2.Name">columnHeader2.Name</a> = “columnHeader2”;<br>
}</p>
<pre><code>    private void button1_Click(object sender, EventArgs e)
    {
        Text = &quot;IndexofKey &quot; + listView1.Columns.IndexOfKey(&quot;columnHeader1&quot;);
    }
</code></pre>
<p>This code works as expected and returns 0.</p>
<p>Thanks<br>
Zheng</p>

---
### Original Solutions
(no solutions)

**Comment by Zheng-Li01** [comment]
**More info:** 
The issue also can reproduce on .NET Framework.
**Core Solution:** 
[CoreReproduce.zip](https://github.com/dotnet/winforms/files/4212650/CoreReproduce.zip)

**Reproduce steps:**
1. Opened the attached application, build and run it.
2. Click the button.

**Expected results**:
Can get the correct index value of columns of ListView control by calling the IndexOfKey() method.
![CoreExpected](https://user-images.githubusercontent.com/38325459/74637741-8a4d5900-51a5-11ea-9e6f-b4b9897777cf.PNG)

**Actual Results:**
Cann't get the correct index value of columns of ListView control by calling the IndexOfKey() method.
![CoreActual](https://user-images.githubusercontent.com/38325459/74637759-946f5780-51a5-11ea-804d-2ee6fe187b5e.PNG)

**Comment by John-Qiao** [comment]
@RussKie I still can reproduce this issue using the latest .NET Core 5.0 SDK with that sample project which Zheng-Li01 provided us, could you confirm it with the latest .NET Core 5.0 SDK?

**Comment by Tanya-Solyanik** [comment]
Need to revert this change because it caused regression in the designer  https://github.com/dotnet/winforms-designer/issues/2441

**Comment by RussKie** [comment]
We need to revert https://github.com/dotnet/winforms/pull/2869

**Comment by dreddy-work** [comment]
@SergeySmirnov-Akvelon , Can you guys take a look and see if this is still and issue and we could take it in 6.0?

**Comment by merriemcgaw** [comment]
@John-Qiao can you check to see if this is still a problem?

**Comment by Tanya-Solyanik** [comment]
The issue as described in this bug is fixed. The designer regression is fixed on the designer level, so this bug can be closed.

**Comment by John-Qiao** [comment]
@merriemcgaw Verified with latest .NET SDK 7.0.100-rc.1.22410.4 build from main branch, this issue still repro in runtime as below:
![TestResult](https://user-images.githubusercontent.com/45864985/184079365-6a288040-8441-40dc-b4ec-ba160ac1d712.png)

**Comment by merriemcgaw** [comment]
@Tanya-Solyanik do you want to take a look and see what is happening here?

**Comment by elachlan** [comment]
I created a minimal repro:
```
[WinFormsFact]
public void ListView_ColumnHeaderCollection_IndexOfKey()
{
    using ListView listView = new();
    using ColumnHeader columnHeader1 = new();
    using ColumnHeader columnHeader2 = new();
    listView.Columns.Add(columnHeader1);
    listView.Columns.Add(columnHeader2);
    Assert.Equal(0, listView.Columns.IndexOfKey("columnHeader1"));
}
```

I think this issue is a designer issue, as it doesn't set a value for `Name`. If the `Name` property is set, then it works. Also `listView.Columns.IndexOf(columnHeader1)` also works.

**Comment by elachlan** [comment]
@merriemcgaw I have outlined my thoughts above on this issue. I believe its a designer issue.

**Comment by merriemcgaw** [comment]
We'll take a look in our designer code.
