### ISSUE TITLE
Test errors in Pipelines include Msbuild environment variable names

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#3091]
See https://dev.azure.com/dnceng/public/_build/results?buildId=607683&view=ms.vss-test-web.build-test-results-tab

![image](https://user-images.githubusercontent.com/1275900/79702279-9b950d80-829b-11ea-8af9-cc1f6fc98f22.png)

We have `$(AgentOsName)` in the logs which should be replaced with the real value

**Comment by RussKie** [comment]
To make it a little more obvious: 
![image](https://user-images.githubusercontent.com/4403806/79712517-6675d300-830e-11ea-8f08-28ff24c678b3.png)

**Comment by lukas-lansky** [comment]
This might be connected to https://github.com/dotnet/arcade/pull/5156. @chcosta, @davidfowl, is this behavior intended? Do winforms need to pass the arguments explicitly now in [the same way aspnetcode does](https://github.com/dotnet/aspnetcore/blob/master/.azure/pipelines/jobs/default-build.yml#L118)?

**Comment by davidfowl** [comment]
Yes https://github.com/dotnet/arcade/pull/5171 needs to be merged asap

**Comment by RussKie** [comment]
dotnet/arcade#5171 has been merged.

**Comment by RussKie** [comment]
This is still an issue...

**Comment by hughbe** [comment]
Maybe we're not updated to latest arcade (https://github.com/dotnet/winforms/pull/3369)

**Comment by RussKie** [comment]
Hmm, I think you may be correct - it was merged 3 weeks ago, but the last we merged an update from arcade was 19 days ago...

**Comment by hughbe** [comment]
Yes I think that may be why I'm also still seeing the `Write-PipelineTelemetryError: not a valid identifier ` errors that were mentioned in https://github.com/dotnet/arcade/pull/5388#discussion_r431737627

**Comment by RussKie** [comment]
With #3369 merged, presume it fixed (second time lucky 😄).
Will re-open, if it's still not fixed.
