### ISSUE TITLE
Error when trying to create Settings file (VB.Net)

### ISSUE THREAD

**Issue by manfromarce** [dotnet/winforms#4308]
* .NET Core Version: 3.1 or 5.0

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
When I create a new .NET Core Windows Forms project in VB.NET and go to Project > Properties > Settings, Visual Studio says that the project doesn't have a default Settings file. However when I click the message to create a new Settings file I get HRESULT_EXCEPTION 0x80070002 (Unable to find specified file). This issue doesn't occur in .NET Core C# projects, nor in .NET Framework.
![Screenshot (103)](https://user-images.githubusercontent.com/45036600/100774322-3e9d3080-3402-11eb-8a52-1a61224aabc4.png)

**Expected behavior:**
When I click the message, I expect a new empty settings file to be created, like in .NET Framework.

**Minimal repro:**
I just created a blank solution and project and the error immediately displays when I go to Project > Properties > Settings and click on the link to create a new settings file. I'm using Visual Studio 16.8.2, I tried to repair my installation and change .NET Core target version but nothing changed.

**Comment by Zheng-Li01** [comment]
There have a similar issue [3346](https://github.com/dotnet/winforms/issues/3346) to track it. and have the comments from klaus:https://github.com/dotnet/winforms/issues/3346#issuecomment-706361699

**Comment by KlausLoeffelmann** [comment]
This has been fixed in 16.9 Preview 3.

**Comment by paul1956** [comment]
@KlausLoeffelmann I don't see any changes with 16.9 Preview 3, it still doesn't work.
![image](https://user-images.githubusercontent.com/12789369/105438262-7ad95a00-5c17-11eb-93cd-82923c64d385.png)
And after a change
![image](https://user-images.githubusercontent.com/12789369/105438348-a8be9e80-5c17-11eb-912d-69821aa0cca0.png)
The file does not exist
and after trying to save
![image](https://user-images.githubusercontent.com/12789369/105438428-d277c580-5c17-11eb-82f8-ee6232d6d561.png)

**Comment by paul1956** [comment]
There appear to be multiple issue app.config in root of Winfoms project needs to be manually changed when upgrading from Framework.
```
    <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
      <section name="CSharpToVBApp.MySettings" type="System.Configuration.ClientSettingsSection, System.Configuration.ConfigurationManager, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" allowExeDefinition="MachineToLocalUser" requirePermission="false" />
```
Needs to be changed to
```
    <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System.Configuration.ConfigurationManager, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" >
        <section name="CSharpToVBApp.MySettings  " type="System.Configuration.ClientSettingsSection, System.Configuration.ConfigurationManager, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" allowExeDefinition="MachineToLocalUser" requirePermission="false" />
```
Using Specialized.StringCollection even on a new project causes the failure

**Comment by merriemcgaw** [comment]
I'm reopening the issue so we can take another look at it. Settings files are something that's on our designer backlog and I don't think would be fully working  yet.

**Comment by paul1956** [comment]
@merriemcgaw It is reported as fixed in 16.9 preview 3 Release Notes.

**Comment by merriemcgaw** [comment]
Thanks for the details. @KlausLoeffelmann let's chat about when we can make this more robust. @dreddy-work, it would be good to include you in the chat.

**Comment by KlausLoeffelmann** [comment]
@merriemcgaw, @RussKie, @KathleenDollard, @paul1956

This issue is _somewhat_ fixed in 16.10. 
I could create a setting file, and also add settings.
I am still getting an error message about a corrupted _App.config_, and we need to figure out, if this is us or Project System.

**Comment by paul1956** [comment]
@KlausLoeffelmann  It look like Preview 3 fixed the ability to edit all System.. types through the UI and save the result that is a big improvement. Related to this is System.Collections.Specialized.StringCollection is not initialized when they are empty. They are Nothing vs Empty. A clear error at least should be added when a setting file is opened with <sectionGroup name="userSettings" Version=4.0.0.0... if it can't be fixed automatically. Should I enter separate bugs on these 2 issues?

**Comment by KlausLoeffelmann** [comment]
> Related to this is System.Collections.Specialized.StringCollection is not initialized when they are empty. They are Nothing vs Empty. A clear error at least should be added when a setting file is opened with <sectionGroup name="userSettings" Version=4.0.0.0... if it can't be fixed automatically.

I am not sure if I understood this correctly. 
Can you clarify what you mean exactly in the context of writing the settings?

What settings issue exactly do you see in Preview 4?

**Comment by paul1956** [comment]
In Framework the default value for a setting of type System.Collections.Specialized.StringCollection is a New collection with count 0, the following code is not necessary
```VB
If My.Settings.IgnoreFileList Is Nothing Then
    My.Settings.IgnoreFileList = New Specialized.StringCollection
End If
```
In core
```
?My.Settings.NewSetting
Nothing
```

**Comment by paul1956** [comment]
Still getting error with Preview 5.
![image](https://user-images.githubusercontent.com/12789369/109074357-87d0e980-76ac-11eb-846e-63cabd8dc7ac.png)

**Comment by RussKie** [comment]
Relates to https://github.com/dotnet/project-system/issues/6784
