### ISSUE TITLE
WinForms HighDPI PerMonitorV2 windows launched on secondary monitor is incorrectly scaled

### ISSUE THREAD

**Issue by Balkoth** [dotnet/winforms#4854]
**.NET Core Version:**

SDK: 5.0.202 (db7cc87d51)
Runtime: 5.0.5 (2f740adc14)

**Problem description:**

If the main application window is not launched on the main monitor it scales wrong, because Form.DeviceDpi has the DPI-Settings of the main monitor.

**Minimal repro:**
- Create new .NET-Core 5.0 WinForms app
- Set Application.SetHighDpiMode(HighDpiMode.PerMonitorV2)
- Open the forms designer for Form1
- Set AutoScaleMode = Dpi
- Set StartPosition = CenterScreen;

-> Build and run the project by launching it not on your primary monitor, but on a secondary monitor with different DPI from the primary monitor. You can do this for example by launching debugging from Visual Studio and quickly focusing a window on another monitor so that this monitor gets the focus.

I have attached a sample project with the repro steps described above here:
[TestDpiChanging.zip](https://github.com/dotnet/winforms/files/6396835/TestDpiChanging.zip)

**Comment by Balkoth** [comment]
Here is a workaround until this is fixed:

```cs
internal const uint WM_DPICHANGED = 0x02E0;

[DllImport("user32.dll")]
internal static extern int GetDpiForWindow(IntPtr hwnd);

[DllImport("user32.dll")]
internal static extern IntPtr SendMessage(IntPtr hWnd, uint msg, IntPtr wParam, ref RECT lParam);

internal static IntPtr MakeLParam(int lowWord, int highWord)
{
  return (IntPtr)((highWord << 16) | (lowWord & 0xffff));
}

[StructLayout(LayoutKind.Sequential)]
internal struct RECT
{
  public int left;
  public int top;
  public int right;
  public int bottom;
}

protected override void OnHandleCreated(EventArgs e)
{
  base.OnHandleCreated(e);

  int realDpi = GetDpiForWindow(this.Handle);
  double scaleFactor = (double)realDpi / (double)this.DeviceDpi;

  int newWidth = (int)(this.Size.Width * scaleFactor);
  int newHeight = (int)(this.Size.Height * scaleFactor);

  int dpiLeft = this.Location.X + ((this.Size.Width - newWidth) / 2);
  int dpiTop = this.Location.Y + ((this.Size.Height - newHeight) / 2);;
  int dpiRight = dpiLeft + newWidth;
  int dpiBottom = dpiTop + newHeight;

  RECT rect = new RECT() { left = dpiLeft, top = dpiTop, right = dpiRight, bottom = dpiBottom };
  SendMessage(this.Handle, WM_DPICHANGED, MakeLParam(realDpi, realDpi), ref rect);
}
```

**Comment by Balkoth** [comment]
I don't know how to say this in simpler words, but there is another method. Just put the windows explorer on the monitor in question and launch the exe via doubleclick from there.

**Comment by dreddy-work** [comment]
No worries. Sample app attached helped understand that you were explicitly setting position on Form to CurrentScreen. Will be looking into it.

**Comment by Ashley-Li** [comment]
Verified this issue with .NET SDK 7.0.100-alpha.1.21479.26, it is fixed that WinForms HighDPI PerMonitorV2 windows launched on secondary monitor is correctly scaled.
![930](https://user-images.githubusercontent.com/56664234/135418965-f191e3b9-b9c3-4dea-9923-44a8bac44da8.PNG)
.

**Comment by Olina-Zhang** [comment]
@dreddy-work  verify this issue in HDPI full testing again on .Net 7.0 build, I found this issue was not fixed well on both .Net 7.0 and .Net 6.0 builds: the Form deviceDpi value is not correct on secondary screen. Please see following testing result:
.Net 7.0 launch test app on **300%** secondary screen directly:
![image](https://user-images.githubusercontent.com/26474449/142401332-aa8dfa8e-2746-41bc-bdd4-0032b73ae23c.png)
.Net 6.0 launch test app on **300%** secondary screen directly:
![image](https://user-images.githubusercontent.com/26474449/142401383-f87de244-e2af-4ef7-830c-ef758f549aa4.png)

**Comment by Olina-Zhang** [comment]
Form is scaled well when launching app in secondary screen directly, we can check it in Spy++, but the control: label gets Form.DeviceDpi value is not correct when launching app in secondary screen directly.
Here is the result when launch app on 300% DPI secondary screen directly:
![image](https://user-images.githubusercontent.com/26474449/142820764-32a0b302-5d19-444e-9203-3855829aae1f.png)
