### ISSUE TITLE
Parent `PerformLayout()` sets negative child `Location` at scale factor >1

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#5774]
* .NET Core Version: **.NET 5.0.9 and .NET 6.0 RC2**

* Have you experienced this same bug with .NET Framework?: **No**

**Problem description:**

The problem is originally reported at
* https://github.com/gitextensions/gitextensions/issues/9402, 
* https://github.com/gitextensions/gitextensions/issues/9491.

### The following report is based on https://github.com/gitextensions/gitextensions/issues/9402

The app on .NET Framework 4.x behaves as expected (150% sf):
![ge-net4x](https://user-images.githubusercontent.com/4403806/133386587-bfc8351c-665b-4682-a2c6-2c7ed8b6440c.gif)

The ported version to .NET 5.0/6.0 exhibit the **issue at scale factor > 100%** (at 100% everything works as expected):
![ge-net60](https://user-images.githubusercontent.com/4403806/133386872-1fea401a-8e10-4834-b01f-d9d0e6fd644b.gif)

During a high level debugging it looks like the panel in question gets assigned negative v-coords when the parent tabpage performs the layout:
![ge-net60-debugger](https://user-images.githubusercontent.com/4403806/133387132-b7f95103-1a14-4312-90c4-ed6d5fe705a0.gif)

**Minimal repro:**

1. set the 
1. clone https://github.com/RussKie/Test-InvisiblePanel
2. open the solution
3. in `Program.cs` set the start form to `FormPush`: `Application.Run(new FormPush());`
3. set the breakpoint in FormPush.Designer.cs line:577
4. run

**Comment by RussKie** [comment]
### This report is based on https://github.com/gitextensions/gitextensions/issues/9491

The app on .NET Framework 4.x behaves as expected (150% sf):
![image](https://user-images.githubusercontent.com/4403806/133388522-01b95f39-fe20-4d3c-afce-3758b9de26b8.png)


The ported version to .NET 5.0/6.0 exhibit the **issue at scale factor > 100%** (at 100% everything works as expected):
![image](https://user-images.githubusercontent.com/4403806/133388611-62bccda7-0820-4dea-b0f9-d262106dae8d.png)


During a high level debugging it looks like the panel in question gets assigned negative v-coords when the parent tabpage performs the layout:
![ge-net60-debugger1](https://user-images.githubusercontent.com/4403806/133390158-4fc3f24a-9774-4047-a819-5413f9f15da5.gif)

**Minimal repro:**

1. set the 
1. clone https://github.com/RussKie/Test-InvisiblePanel
2. open the solution
3. in Program.cs set the start form to FormPush: Application.Run(new FormCreateBranch());
4. set the breakpoint in FormCreateBranch.Designer.cs line:244
5. run

**Comment by dreddy-work** [comment]
Issue is with the Anchoring of the Panel. We have multiple issues int repo with same root cause. I am prioritizing this issue now and see if i can get something out for GA. Meanwhile, @RussKie , if you could align the panel in GitExtensions without anchoring, it should work for time being.

**Comment by dreddy-work** [comment]
We introduced a opt-in flag `EnableAnchorLayoutHighDpiImprovements `that is now become default in core. Changes covered under this flag are root cause of this issue. you can repro this issue by enabling this flag in .NET framework as well.

**Comment by RussKie** [comment]
So basically the regression lies somewhere here, right?
https://github.com/dotnet/winforms/blob/a88610b7c10afa8a1353322e9fb8ecb4fc9580b0/src/System.Windows.Forms/src/System/Windows/Forms/Layout/DockAndAnchorLayout.cs#L672-L721

Here's the .NET Framework: https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/Layout/DockAndAnchorLayout.cs,581

**Comment by Philip-Wang01** [comment]
Verified this issue with latest .NET SDK 7.0.100-alpha.1.21566.13 build, this issue has been fixed.

![image](https://user-images.githubusercontent.com/86937911/142136464-17e53f94-d516-4d3a-b5b4-76ef0a0ab9a3.png)

**Comment by Lydia-Shi** [comment]
Verified this issue with VS 17.0.2 Preview 1.0 [31923.300.d17.0] + .NET 6.0.101-servicing.21569.4 build, this issue is fixed.
![Git](https://user-images.githubusercontent.com/54019172/143540549-2137ad9a-ce73-4b38-b65f-559d9c906f1d.gif)
![image](https://user-images.githubusercontent.com/54019172/143540637-a5b15388-f3a5-448a-bef0-e9f48eede38a.png)

**Comment by RussKie** [comment]
This sample is still broken https://github.com/dotnet/winforms/issues/5774#issuecomment-919771932
Whilst the left border is correctly aligned, the right border isn't calculated correctly. So now instead of this:
![image](https://user-images.githubusercontent.com/4403806/133388611-62bccda7-0820-4dea-b0f9-d262106dae8d.png)
I get this:
![image](https://user-images.githubusercontent.com/4403806/145152044-4a56073b-945f-4ae0-93c2-c72c8941954d.png)

**Comment by dreddy-work** [comment]
@Lydia-Shi , can you confirm on this with latest WinForms bits from main branch? and if it repro, can you track what change causing it?

**Comment by Lydia-Shi** [comment]
@dreddy-work Verified this issue with latest .NET 7.0.100-alpha.1.21568.2 + private dlls built from main branch in Winforms repro, this issue is fixed after resized From, and we also get same results without private dlls, please see below GIF:
![Fixed](https://user-images.githubusercontent.com/54019172/146115004-d7352064-c430-440f-b757-d920a35f04ad.gif)

**Comment by dreddy-work** [comment]
> @dreddy-work Verified this issue with latest .NET 7.0.100-alpha.1.21568.2 + private dlls built from main branch in Winforms repro, this issue is fixed after resized From, and we also get same results without private dlls, please see below GIF: ![Fixed](https://user-images.githubusercontent.com/54019172/146115004-d7352064-c430-440f-b757-d920a35f04ad.gif)

It seems there is an issue with the container size holding those controls. behavior is not same as Framework.

**Comment by Lydia-Shi** [comment]
@dreddy-work Verified "PushForm" in latest .NET 7.0.100-alpha.1.21568.2, "FormPush" form shows incorrectly after clicking "Shows options" in 300%,200%,175%, but shows correctly in 150%, so please help us to confirm if there are some errors about control size in sample project.
![ForPush](https://user-images.githubusercontent.com/54019172/147321198-8b49205a-5120-4166-aaf6-4521fe24446a.gif)
![image](https://user-images.githubusercontent.com/54019172/147321279-d764bb19-9b26-4a93-a6b6-b33428bedf8e.png)

**Comment by RussKie** [comment]
@merriemcgaw @dreddy-work this is a real .NET migration blocker for Git Extensions project (>160K users).

**Comment by RussKie** [comment]
@dreddy-work I have update the repro to multi target .NET Fx 4.8, .NET 5, .NET 6 and .NET 7

https://user-images.githubusercontent.com/4403806/152923361-16d37a56-a431-484e-b168-56a80066f62f.mp4
