### ISSUE TITLE
Form Layout (control size) bug with Anchor = Top | Bottom

### ISSUE THREAD

**Issue by kirsan31** [dotnet/winforms#6041]
* .NET Core Version: all up to 6.0 rc2

* Have you experienced this same bug with .NET Framework?: Yes

**Problem description:**
Form, with any control and `Anchor = AnchorStyles.Top | AnchorStyles.Bottom`.
1. Remember form size and distance from bottom of this control to the bottom of the form.
2. Resize the form that this control become off-screen (if any part of the control still be visible - all work as expected).
3. Add any new control to the form (press `A` key in repro project below).
4. Resize form back to dimensions you remembered on step 1. And see that distance from bottom of the control to the bottom of the form is changed.

https://user-images.githubusercontent.com/17767561/138507989-b39e3f65-96b3-4385-abbc-8f2fa42f2a42.mp4

**Expected behavior:**
Distance from bottom of the control to the bottom of the form must be constant.

I think that the problem is that when new control added, new layout performs from scratch and therefore can't properly process the control with zero height and location outside of the current form dimensions. You can even emulate this in designer:

https://user-images.githubusercontent.com/17767561/138549216-991c7253-80c5-42ca-a049-4b66bc2a5a86.mp4

In the first time it's absolutely reasonable  - no way to do this *right*. But I am wonder, if we already have properly align, is it possible not to reset it on `Layout`?

**Minimal repro:**
[FormLayoutBug.zip](https://github.com/dotnet/winforms/files/7400787/FormLayoutBug.zip)

**Comment by dreddy-work** [comment]
@kirsan31 , This should be resolved with latest binaries from main branch.

**Comment by kirsan31** [comment]
@dreddy-work 
You mentioned that this is fixed in https://github.com/dotnet/winforms/pull/6122.

> This issue was introduced in .NET Framework 4.8. Control AnchorInfo is used in the determination of Location of the Control. AnchorInfo was miscalculated (ignored AnchorStyle property) when controls scaled on higher DPI settings and thus location OFF as demonstrated in the linked issue. In this change, we will be checking the AnchorStyles before overriding the AnchorInfo.

But:
- this issue is not DPI related.
- this issue is repro with .NET Framework 4.7.2 too.

**Comment by dreddy-work** [comment]
Our test team ran this scenario and they do not see this issue with latest binaries. Let me check this myself and until then i will keep this open.

**Comment by dreddy-work** [comment]
@kirsan31 , i tried myself with latest binaries from main branch and issue doesn't repo.  It was my mistake to say it was introduced in 4.8. it was actually introduced at teh end of 2016 and that timeline aligns with 4.7.

**Comment by dreddy-work** [comment]
regression introduced here (internal reference)https://devdiv.visualstudio.com/DevDiv/_workitems/edit/275828

**Comment by Olina-Zhang** [comment]
Verified this issue with latest .NET SDK 7.0.100-alpha.1.21566.13 build, it is fixed:
![GHIssue6041_withPrivates](https://user-images.githubusercontent.com/26474449/142148288-239c9b9f-0a3f-43d6-b245-c4b8db2c00e3.gif)

**Comment by kirsan31** [comment]
@dreddy-work @Olina-Zhang 
I have several bugs that I think is related to this one. I have checked them with .Net 7.0 and they are not fixed there :(
Then I have checked exactly this bug (repro from 1 post)  with .Net 7.0 `dotnet-sdk-7.0.100-alpha.1.22060.9-win-x64.exe` and it's not fixed too:

https://user-images.githubusercontent.com/17767561/148945078-726d3c08-04ea-477c-9589-982781ad0142.mp4

**Comment by dreddy-work** [comment]
> @dreddy-work @Olina-Zhang I have several bugs that I think are related to this one. I have checked them with .Net 7.0 and they are not fixed there :( Then I have checked exactly this bug (repro from 1 post) with .Net 7.0 `dotnet-sdk-7.0.100-alpha.1.22060.9-win-x64.exe` and it's not fixed too:

@Olina-Zhang , can you help validate this?

> P.s. I still [can't build 6.0 targets with 7.0 sdk](https://github.com/dotnet/winforms/issues/3202#issuecomment-978891569) :(

@kirsan31 , can you elaborate on this?

**Comment by kirsan31** [comment]
@dreddy-work 
> can you elaborate on this?

After Installing net7 sdk (all versions up to `dotnet-sdk-7.0.100-alpha.1.22060.9-win-x64.exe`) the build of `net6.0`/`net6.0-windows` targets are failed with dozens of errors if we will use net7 sdk for build (use _preview of net sdk_ option in VS).
Also `BenchmarkDotNet` will fail to build `net6.0`/`net6.0-windows` benchmarks until you uninstall net7 sdk.
`net7.0; net7.0-windows; net5.0; net5.0-windows; netcoreapp3.1; net472` are fine.

I posted about this [here](https://github.com/dotnet/winforms/issues/3202#issuecomment-978891569) and then [here](https://github.com/dotnet/sdk/issues/22752#issuecomment-979035894).

**Comment by dreddy-work** [comment]
> I posted about this [here](https://github.com/dotnet/winforms/issues/3202#issuecomment-978891569) and then [here](https://github.com/dotnet/sdk/issues/22752#issuecomment-979035894).

May be we have to wait for https://github.com/dotnet/sdk/pull/23293 to finish. Did you raise issue in SDK repo? can you link it here?

**Comment by kirsan31** [comment]
> May be we have to wait for [dotnet/sdk#23293](https://github.com/dotnet/sdk/pull/23293) to finish.

May be :man_shrugging:

> Did you raise issue in SDK repo? can you link it here?

I found similar (I think so...) [issue](https://github.com/dotnet/sdk/issues/22752) and posted a [comment](https://github.com/dotnet/sdk/issues/22752#issuecomment-979035894) there...

**Comment by kirsan31** [comment]
I will wait on clarifications with this one to understand what to do with other bugs (related or not) ...
P.s. net6 build issues will be fixed with https://github.com/dotnet/installer/pull/12654.

**Comment by Olina-Zhang** [comment]
> @Olina-Zhang , can you help validate this?
Sorry for missing this issue verification again, will update it tomorrow when the HDPI machine is ready.

**Comment by kirsan31** [comment]
@Olina-Zhang 
> Sorry for missing this issue verification again, will update it tomorrow when the HDPI machine is ready.

This issue is not related to HDPI.

**Comment by Olina-Zhang** [comment]
Verified this issue in the latest .Net 7.0 SDK build, it can reproduce now, re-open this one @dreddy-work 
![Repro](https://user-images.githubusercontent.com/26474449/149127831-5afc1c52-f175-4154-bce3-3ae9f42d9f2f.gif)

**Comment by kirsan31** [comment]
@dreddy-work 
Also, I see https://github.com/dotnet/winforms/pull/6140 servicing PR with 6.01 Milestone. In 6.0.1 this bug is repro too.

**Comment by RussKie** [comment]
@dreddy-work was this fixed, or are there more fixes expected to resolve this issue?

**Comment by dreddy-work** [comment]
> @dreddy-work was this fixed, or are there more fixes expected to resolve this issue?

I will have to go over the history one more time here.  I did link the fix that regressed here which was with anchor calculations.  Will have to check.

**Comment by kirsan31** [comment]
Just tested it in 7.03 - not fixed.
