### ISSUE TITLE
Anchors of user control don't work when scaling on high DPI

### ISSUE THREAD

**Issue by 2mik** [dotnet/winforms#6381]
* .NET Core Version: 
6.0

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

When components are inside a user control, their anchors work incorrect when scaling. It affects a project a lot, because using docking instead of anchors for components inside a user control is difficult in some cases.
Scale 100%
![scale100](https://user-images.githubusercontent.com/9930867/146959607-0dc9603a-ef6d-4b9f-ad77-1a8167df6f87.png)
Scale 150%
![scale150](https://user-images.githubusercontent.com/9930867/146959627-40cfaf0e-9a22-4482-940c-1d426e154929.png)

**Expected behavior:**
Anchors works well like it was on classic .NET.

**Minimal repro:**
Sample app is attached. Run it when screen is scaled 150% to reproduce the bug.
[ControlScalingBug.zip](https://github.com/dotnet/winforms/files/7756538/ControlScalingBug.zip)

**Comment by deng0** [comment]
This is not a new problem of .NET Core.

The same already happened with .NET Framework.
I've adjusted your repro project to use .NET Framework and the same problem happens there too:
[ControlScalingBug_NET48.zip](https://github.com/dotnet/winforms/files/7853762/ControlScalingBug_NET48.zip)

But still it would be nice if the bug would someday be fixed.

For now it's best to use the following workaround:
Whenever creating a UserControl where inside the UserControl you want to anchor controls, first create a panel inside the UserControl and set the panel to Dock Fill. Then anchor the controls inside that panel and not directly inside the UserControl.
This way everything should be correctly DPI scaled when the UserControl is used in a Form.

**Comment by 2mik** [comment]
My case works correctly on classic .NET, but doesn't work on .NET Core.
May be classic .NET also has issues with anchors, but its behavior differs comparing to .NET core.

**Comment by deng0** [comment]
> My case works correctly on classic .NET, but doesn't work on .NET Core. 

Have you looked at the adjusted repro I've created? That is your case on classic .NET and it has the same problem, doesn't it?
It might be important to know if this is in fact a regression with .NET Core or not in order to fix it.

**Comment by dreddy-work** [comment]
@2mik , issue is not clear to me. Looking at the source, size of the text box is serialized so in the user control. Can you create a gif with repro scenario to understand little better here?

**Comment by 2mik** [comment]
Could you suggest a free gif recording tool?

**Comment by RussKie** [comment]
https://www.screentogif.com/

**Comment by 2mik** [comment]
![Control Anchors](https://user-images.githubusercontent.com/9930867/155470477-e860d8d1-5db8-4af9-86a0-b098c0f5e00a.png)
![Control Bad](https://user-images.githubusercontent.com/9930867/155470493-736192fe-f9e9-4b27-b643-43ec846e2ba8.gif)
You can see that there are anchors on the control. But the anchors does not work on 4K with 150% scaling.

**Comment by RussKie** [comment]
This looks somewhat similar to the outstanding issue described in https://github.com/dotnet/winforms/issues/5774.

**Comment by 2mik** [comment]
The mentioned #5774 "Parent PerformLayout() sets negative child Location" is too specific and understandable only for WinForms developers/support team. May be this is the same, may be not.

**Comment by John-Qiao** [comment]
Verified with 7.0.100-preview.5.22267.11 from main branch, this issue has been fixed that the Anchors of user control works when scaling on high DPI now.

![TestResult](https://user-images.githubusercontent.com/45864985/169223814-0ca496c2-63f7-4c58-a7ea-a64a770e1e87.gif)

**Comment by 2mik** [comment]
Thanks a lot!

**Comment by Cassie-Li01** [comment]
Verified this issue on .NET SDK 7.0.100-preview.5.22305.3 TP, it is fixed. Gif as above.

**Comment by 2mik** [comment]
@dreddy-work, thank you for keeping me updated.

**Comment by Amy-Li03** [comment]
Verified this on .NET latest build: 8.0.100-alpha.1.23055.16, issue is still reproducing. Please see following video:
![Repro](https://user-images.githubusercontent.com/62929087/210971688-e2919016-ec78-4546-a988-a545d9039727.gif)

**Comment by dreddy-work** [comment]
Thanks @Amy-Li03. Reopening it now to investigate further.

**Comment by dreddy-work** [comment]
I take a look, while cleaning up that code, we made a mistake in determining the .NET apps vs Framework apps and new code path is not executed default. Pushing the fix. THanks @Amy-Li03.

**Comment by Amy-Li03** [comment]
Verified this with privates built from PR: [#8467](https://github.com/dotnet/winforms/pull/8467), issue was fixed, the Anchors of user control works well when scaling on high DPI.
![Fixed](https://user-images.githubusercontent.com/62929087/211254098-7cbe188d-5eeb-4252-892c-8bd96933a6a6.gif)

**Comment by Philip-Wang01** [comment]
Verified with .NET SDK 8.0.100-alpha.1.23068.16 build from main branch, this issue has been fixed that the Anchors of user control works when scaling on high DPI now.
