### ISSUE TITLE
6.0.2 SDK update has broken WinForms apps

### ISSUE THREAD

**Issue by EatonZ** [dotnet/winforms#6663]
ℹ️  **UPDATE:** [Workaround here for those who need it.](https://github.com/dotnet/core/issues/7176)

. . .

There appears to be a critical problem with the new 6.0.2 update which makes apps compiled with it fail to start on machines running 6.0.1.

To reproduce, do the following:
1. Visit Windows Update to update the runtime on your **dev machine**, and also update Visual Studio 2022 using Visual Studio Installer.
2. On a **client/test machine**, install the 6.0.1 desktop runtime. [Direct Link](https://dotnetcli.azureedge.net/dotnet/WindowsDesktop/6.0.1/windowsdesktop-runtime-6.0.1-win-x64.exe)
3. On your dev machine, create a new WinForms project, build it and copy the executable files to the client/test machine.
4. Run it and it will not start. Event logs show the following:
```
Application: WinFormsApp1.exe
CoreCLR Version: 6.0.121.56705
.NET Version: 6.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException: Could not load file or assembly 'System.Windows.Forms, Version=6.0.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'System.Windows.Forms, Version=6.0.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at WinFormsApp1.Program.Main()
```

This problem did not happen on .NET 5. I was under the impression patch versions are generally compatible with each other, and I use `<RollForward>LatestPatch</RollForward>` in my real app, but even with that setting it still crashes.

This is a blocking issue for me because if I distribute an update for my app built on 6.0.2 and the client is still running 6.0.1, that will be bad if the app suddenly stops working.

**Comment by dreddy-work** [comment]
@RussKie , is this because we are shipping SDKs with each servicing release now?

**Comment by RussKie** [comment]
@dreddy-work  we do not ship the SDKs in servicing releases, we ship the ref packs.

@EatonZ you're building an app on a higher version of .NET and trying to execute on a lower version. How do you configure SDKs in [global.json](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json)?

**Comment by RussKie** [comment]
@EatonZ it is indeed a major issue with the 6.0.2 servicing release. The assembly versions have been revved from 6.0.0 to 6.0.2, which is causing the issue you're facing. The team is currently discussing different ways this issue may be addressed and ways we can minimise the drama for developers like yourself. Unfortunately there's no easy way out here.
In mean time please build your applications against 6.0.0 or 6.0.1.

**Comment by RussKie** [comment]
I believe you can install 6.0.1 from https://dotnet.microsoft.com/en-us/download/dotnet/6.0. In the global.json you can pin the SDK to 6.0.1
```json
{
  "sdk": {
    "version": "6.0.101",
    "rollForward": "disable"
  }
}
```

**Comment by EatonZ** [comment]
@RussKie Thank you, everything is back in a working state for me now.
It seems like the best way to fix would be to put out a new update that doesn't bump the versions. Hopefully you can do that soon to avoid a lot of people compiling incompatible software on this version.

**Full workaround steps for others who may need help:**
1. Make sure Windows and Visual Studio have installed the latest Patch Tuesday updates. Check Windows Update, and the Visual Studio Installer.
2. Download and install the 6.0.1 SDK ([64-bit download](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.101-windows-x64-installer), [32-bit download](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.101-windows-x86-installer)).
3. Create a `global.json` file with the contents @RussKie commented [here](https://github.com/dotnet/winforms/issues/6663#issuecomment-1034371295), and put that file beside your project's .sln file.

That's it. When you debug your app you may notice it's still loading 6.0.2 DLLs, but when you run the app on a system with the 6.0.1 runtime, it will work/not crash.

**Comment by absid89** [comment]
> I believe you can install 6.0.1 from https://dotnet.microsoft.com/en-us/download/dotnet/6.0. In the global.json you can pin the SDK to 6.0.1
> 
> ```json
> {
>   "sdk": {
>     "version": "6.0.101",
>     "rollForward": "disable"
>   }
> }
> ```

i have same problem after visual studio update. on clients installed 6.0.1 runtime, and all got a crash after run app
thx, i will try your solution

**Comment by kirsan31** [comment]
@EatonZ WoW - thanks foк discovering this first - it will save us a certain amount of nerve cells :)))

**Comment by absid89** [comment]
> That's it. When you debug your app you may notice it's still loading 6.0.2 DLLs, but when you run the app on a system with the 6.0.1 runtime, it will work/not crash.

thx for explain, otherwise no matter what I did, the version of the environment did not change to 6.0.1

**Comment by RussKie** [comment]
For an available workaround please refer to https://github.com/dotnet/core/issues/7176.

**Comment by SimonCropp** [comment]
so when this is fixed, my app build against the latest 6.0.* sdk will be able to run on a machine with only 6.0.0 installed?

**Comment by RussKie** [comment]
Any apps built on 6.0.n will work on the latest 6.0.m. However apps built on 6.0.2+ won't work on 6.0.0 or 6.0.1.

**Comment by RussKie** [comment]
https://github.com/dotnet/wpf/pull/6101#issuecomment-1039089267 contains some useful info.

**Comment by SimonCropp** [comment]
> Any apps built on 6.0.m will work on the latest 6.0.n (where n > m). However apps built on 6.0.2+ won't work on 6.0.0 or 6.0.1.

so if i interpret that correctly, if anyone wanst to leverage some new features/fixes of an sdk, it has to be considered a breaking change for the deployed app?

**Comment by RussKie** [comment]
Yes, in some scenarios it will be a breaking change.

**Comment by SimonCropp** [comment]
in some scenarios? in what scenarios would it not be considered a breaking change?

**Comment by RussKie** [comment]
> in what scenarios would it not be considered a breaking change?

When an app built against 6.0.2+ not run on 6.0.0 or 6.0.1.

**Comment by SimonCropp** [comment]
i am talking from the perspective of the app producer. it would seem any time they update their sdk, they also need to force all consumers to update their runtime, hence always breaking

**Comment by RussKie** [comment]
The end users need to be on at least 6.0.2, after that it should BAU. That is, if an app producer builds against 6.0.2 or 6.0.6 should, the app would run on any runtime starting from 6.0.2.

**Comment by SimonCropp** [comment]
>  That is, if an app producer builds against 6.0.2 or 6.0.6, the app would run on any runtime starting from 6.0.2.

ok cool. that was my hope.

**Comment by DavidWiseman** [comment]
If I run my .NET 6 app on a machine without .NET 6 installed, I'm prompted to install it which is great.  If I later compile with 6.0.2 which happens automatically just by upgrading VS.  Then the app fails silently.  I have to check the event viewer for an error message - do some googling and try to figure out what the problem is.  

If a newer runtime is required I don't think it would be as big problem if it prompted you to install the new version.  Or if this was treated as a new .NET framework version where you have to explicitly change the target framework in Visual Studio.

I guess this will be less of an issue over time as more clients have 6.0.2 installed.  For now I don't want to upgrade and will use the workaround.

**Comment by EatonZ** [comment]
6.0.3 is out now. Is this considered fixed?

**Comment by dreddy-work** [comment]
> 6.0.3 is out now. Is this considered fixed?

It should. We will cross verify and close it.

**Comment by tomaszmalik** [comment]
The issue is **critical** and it is **not fixed in 6.0.3**. 
It's hard to believe that we have to wait another month for that easy fix.

**Comment by kirsan31** [comment]
> The issue is **critical** and it is **not fixed in 6.0.3**. It's hard to believe that we have to wait another month for that easy fix.

Really? Our app build with 6.0.3 work fine on machines with 6.0.2... 🤷‍♂️

**Comment by tomaszmalik** [comment]
> Really? Our app build with 6.0.3 work fine on machines with 6.0.2... 🤷‍♂️

That's because .NET 6.0.2 and .NET 6.0.3 has System.Windows.Forms with version 6.0.2.
.NET 6.0.0 and .NET 6.0.1 has System.Windows.Forms with version 6.0.0.
So error occur for user with .NET version 6.0.0 or 6.0.1, who uses apps compiled with 6.0.2 or 6.0.3.

**Comment by kirsan31** [comment]
> > Really? Our app build with 6.0.3 work fine on machines with 6.0.2... 🤷‍♂️
> 
> That's because .NET 6.0.2 and .NET 6.0.3 has System.Windows.Forms with version 6.0.2. .NET 6.0.0 and .NET 6.0.1 has System.Windows.Forms with version 6.0.0. So error occurs for user with .NET version 6.0.0 or 6.0.1, who uses apps compiled with 6.0.2 or 6.0.3.

And this is by design I think...
https://github.com/dotnet/winforms/issues/6663#issuecomment-1039910644 https://github.com/dotnet/winforms/issues/6663#issuecomment-1040990481 https://github.com/dotnet/winforms/issues/6663#issuecomment-1041002991

**Comment by tomaszmalik** [comment]
> And this is by design I think... [#6663 (comment)](https://github.com/dotnet/winforms/issues/6663#issuecomment-1039910644) [#6663 (comment)](https://github.com/dotnet/winforms/issues/6663#issuecomment-1040990481) [#6663 (comment)](https://github.com/dotnet/winforms/issues/6663#issuecomment-1041002991)

No, it's not, it's a bug. :) It seems that it would not be fixed, as it was explained here:
https://github.com/dotnet/wpf/pull/6101#issuecomment-1039089267
I understand the problem, but there should be official warning and some explanation in release notes.
The issue is still open ...

**Comment by dreddy-work** [comment]
> The issue is **critical** and it is **not fixed in 6.0.3**. 

@RussKie to confirm the fix propagated to 6.0.3 installer.

**Comment by EatonZ** [comment]
I checked and the 6.0.3 System.Windows.Forms dll is versioned 6.0.2.0. That is what they said would happen, so it appears the issues is fixed.

My advice would be to wait a while for users' computers to update with this new version before building again with 6.0.2+. Building on 6.0.1 is the safest option for now.

**Comment by RussKie** [comment]
> The issue is **critical** and it is **not fixed in 6.0.3**.
> It's hard to believe that we have to wait another month for that easy fix.
>
> That's because .NET 6.0.2 and .NET 6.0.3 has System.Windows.Forms with version 6.0.2.
> .NET 6.0.0 and .NET 6.0.1 has System.Windows.Forms with version 6.0.0.
> So error occurs for user with .NET version 6.0.0 or 6.0.1, who uses apps compiled with 6.0.2 or 6.0.3.

This _**is**_ the fix. Between the bad and the worse, it was the best option available. Please refer to https://github.com/dotnet/winforms/pull/6667 and https://github.com/dotnet/wpf/pull/6101#issuecomment-1039089267 for more details as to why this is considered a fix. Sadly, if you're shipping Windows Desktop apps targeting 6.0.0 or 6.0.1 you'll need to recompile for 6.0.2 or later. Likewise, if users don't have at least 6.0.2 runtime installed, they won't be able to run your apps compiled on 6.0.2 or later.

> Building on 6.0.1 is the safest option for now.

[6.0.1](https://devblogs.microsoft.com/dotnet/december-2021-updates/#security), [6.0.2](https://devblogs.microsoft.com/dotnet/february-2022-updates/#security) and [6.0.3](https://devblogs.microsoft.com/dotnet/march-2022-updates/#security) are MSRC releases, and users are encouraged to update to the latest runtime/SDK available.

**Comment by lukos** [comment]
This is all very depressing. .Net is 20 years old and it seems like MS still can't get the versioning of assemblies correct. I honestly think I spent 50% of my time coding an app and the rest trying to get builds and deployments working. It is not acceptable for a company with as much experience and expertise as MS to just say, "yeah this was wrong but we'll sort it out later". Not everyone has the luxury of rebuilding things or getting customers to update runtimes as easily as that.

Not that this is the issue I had recently with my app but it leaves a really poor experience for people like me who really do like .Net and yet their first attempt at a dotnet core winforms app falls at the first hurdle and I still don't know why.

**Comment by TcNobo** [comment]
Adding .NET 6.0.3 as a requirement fixed the issues I was experiencing. The TcNo Account Switcher I'm working on includes a C++ fallback to verify system requirements are met, and will auto-download new runtimes. While it's not a huge issue to me, it was incredibly confusing that it just broke after updating VS/Windows...
