### ISSUE TITLE
Changing MinimumSize of Form activates the form

### ISSUE THREAD

**Issue by tbambuch** [dotnet/winforms#7251]
### .NET version

6.0

### Did it work in .NET Framework?

No

### Issue description

In Form.MinimumSize setter, `SetWindowPos `is called with `User32.SWP.NOZORDER` flag. I suppose `User32.SWP.NOZORDER | User32.SWP.NOACTIVATE` should be used, since there is no point in activating the form when MinimumSize changes

The problem I was facing was that MinimumSize and MaximumSize are not scaled when dpi changes (not sure why, in my opinion they should be), so I added scaling of them into `OnDpiChanged`. 
An now the magic happened: changing MinSize activates the form, which looks up the ActiveControl to set focus to. But dpi change arrives too early and the control is not visible yet, so ActiveControl remained null on nonprimary screen, but worked fine on the primary one :/

### Steps to reproduce

-

**Comment by merriemcgaw** [comment]
Our recommendation is to not change the activation behavior of MinimumSize/MaximumSize. However, we should go ahead and scale those properties.

**Comment by Cassie-Li01** [comment]
Verified on TP build 7.0.100-rc.1.22425.12, it is fixed. Details as below:
<html>
<body>


Scenarios | Result

Scenario1: .Net 7.0, and "System.Windows.Forms.ScaleTopLevelFormMinMaxSizeForDpi": true. 100% primary screen,  300% secondary screen | Issue is fixed
Scenario2: .Net 7.0, and "System.Windows.Forms.ScaleTopLevelFormMinMaxSizeForDpi": false. 100% primary screen,  300% secondary screen | Issue is fixed


</body>
</html>

![GetImage](https://user-images.githubusercontent.com/96758262/187184002-debfa51d-17d7-4a14-aef6-a7d2a840e3f3.png)
![GetImage (1)](https://user-images.githubusercontent.com/96758262/187184004-23c358f9-31a5-45ed-8abf-c7b232e53519.png)

**Comment by Amy-Li03** [comment]
Verified on .NET 8.0 latest build from main branch: NET 8.0.100-alpha.1.22451.15, **Scenario1 was fixed, but Scenario2 is still reproducing.**

**Scenario1**: .Net 7.0, and "System.Windows.Forms.ScaleTopLevelFormMinMaxSizeForDpi": true. 100% primary screen,  300% secondary screen.
**Scenario2**: .Net 7.0, and "System.Windows.Forms.ScaleTopLevelFormMinMaxSizeForDpi": false. 100% primary screen, 300% secondary screen.
When moving to 300% secondary screen, test result for Scenario2 as below.
![image](https://user-images.githubusercontent.com/62929087/188113579-6b00eddb-c706-47be-8de7-fe89d00fd9f9.png)

**Comment by Amy-Li03** [comment]
Verified on .NET 8.0 latest build from main branch: NET 8.0.100-alpha.1.22451.15, **Scenario1 was fixed, but Scenario2 is still reproducing.**

**Scenario1**: .Net 7.0, and "System.Windows.Forms.ScaleTopLevelFormMinMaxSizeForDpi": true. 100% primary screen,  300% secondary screen.
**Scenario2**: .Net 7.0, and "System.Windows.Forms.ScaleTopLevelFormMinMaxSizeForDpi": false. 100% primary screen, 300% secondary screen.
When moving to 300% secondary screen, test result for Scenario2 as below.
![image](https://user-images.githubusercontent.com/62929087/188113579-6b00eddb-c706-47be-8de7-fe89d00fd9f9.png)

**Comment by Amy-Li03** [comment]
Verified on .NET 8.0 latest build from main branch: NET 8.0.100-alpha.1.22451.15, **Scenario1 was fixed, but Scenario2 is still reproducing.**

**Scenario1**: .Net 7.0, and "System.Windows.Forms.ScaleTopLevelFormMinMaxSizeForDpi": true. 100% primary screen,  300% secondary screen.
**Scenario2**: .Net 7.0, and "System.Windows.Forms.ScaleTopLevelFormMinMaxSizeForDpi": false. 100% primary screen, 300% secondary screen.
When moving to 300% secondary screen, test result for Scenario2 as below.
![image](https://user-images.githubusercontent.com/62929087/188113579-6b00eddb-c706-47be-8de7-fe89d00fd9f9.png)

**Comment by Amy-Li03** [comment]
Verified on .NET 8.0 latest build from main branch: NET 8.0.100-alpha.1.22451.15, **Scenario1 was fixed, but Scenario2 is still reproducing.**

**Scenario1**: .Net 7.0, and "System.Windows.Forms.ScaleTopLevelFormMinMaxSizeForDpi": true. 100% primary screen,  300% secondary screen.
**Scenario2**: .Net 7.0, and "System.Windows.Forms.ScaleTopLevelFormMinMaxSizeForDpi": false. 100% primary screen, 300% secondary screen.
When moving to 300% secondary screen, test result for Scenario2 as below.
![image](https://user-images.githubusercontent.com/62929087/188113579-6b00eddb-c706-47be-8de7-fe89d00fd9f9.png)

**Comment by Amy-Li03** [comment]
Verified on .NET 8.0 latest build from main branch: NET 8.0.100-alpha.1.22451.15, **Scenario1 was fixed, but Scenario2 is still reproducing.**

**Scenario1**: .Net 7.0, and "System.Windows.Forms.ScaleTopLevelFormMinMaxSizeForDpi": true. 100% primary screen,  300% secondary screen.
**Scenario2**: .Net 7.0, and "System.Windows.Forms.ScaleTopLevelFormMinMaxSizeForDpi": false. 100% primary screen, 300% secondary screen.
When moving to 300% secondary screen, test result for Scenario2 as below.
![image](https://user-images.githubusercontent.com/62929087/188113579-6b00eddb-c706-47be-8de7-fe89d00fd9f9.png)

**Comment by dreddy-work** [comment]
When flag is set to false, you see existing behavior and that is by design. We wanted to make sure we are not breakign existing application that may have worked around this issue.
