### ISSUE TITLE
DataGridView refresh problem after scrolling when it is in Virtual mode

### ISSUE THREAD

**Issue by mocakturk** [dotnet/winforms#9207]
### .NET version

.NET 7.0

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

I didn't try.
I directly migrate from .NET framework 4.8 to .NET 7.

### Issue description

Datagridview does not render the cells correctly after scrolling. It is in virtual mode.
There was no problem when I was using .NET framework 4_8.
![datagridview_issue](https://github.com/dotnet/winforms/assets/106665359/84aab4f0-fd4c-4607-92ed-f5c3ef8e3d6b)

### Steps to reproduce

Create a datagridview in virtual mode. Make it's size small, so that both horizontal and vertical scrollbars are visible.

**Comment by elachlan** [comment]
@dreddy-work another highDPI issue.

**Comment by elachlan** [comment]
@Olina-Zhang Could your team please test this? I wonder if it has already been fixed in .NET8

**Comment by dreddy-work** [comment]
> @dreddy-work another high DPI issue.

I do not think so from nature of it. Seems rendering issue. @Olina-Zhang, can you confirm if this has issue with other DPI modes other than `DpiUnawareGdiScaled` ?

**Comment by Philip-Wang01** [comment]
@elachlan Verified this issue in the latest .Net 8.0 SDK build: 8.0.100-preview.6.23301.14, this issue still repro.
@dreddy-work This issue only repro in `DpiUnawareGdiScaled` mode, not repro on other DPI modes.


[TestDpiUnawareGdiScaled.zip](https://github.com/dotnet/winforms/files/11632230/TestDpiUnawareGdiScaled.zip)

https://github.com/dotnet/winforms/assets/86937911/b9d5bad9-1a45-4408-abeb-c523808890a6

**Comment by mocakturk** [comment]
Issue happens in both virtual and non-virtual grids when **DpiUnawareGdiScaled** mode is active.

**Comment by merriemcgaw** [comment]
WinForms doesn't take any specific actions when it comes to GDIScaled. Our recommendation would be to use SystemAware for applications. We can take a look at some point in the future, but due to resource constraints, and the improvements in SystemAware we'd recommend trying that first.
