### ISSUE TITLE
sdk warning on nuget package Microsoft.CodeAnalysis.CodeStyle

### ISSUE THREAD

**Issue by elachlan** [dotnet/winforms#9855]
I followed all the instructions for installing and starting VS from a script, but I get 91 of the errors below. I do have ,Net 4.8 installed from VS installer but where do I get new compiler?
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS9057	The analyzer assembly 'C:\Users\PaulM\Source\Repos\winforms\.dotnet\sdk\8.0.100-preview.7.23376.3\Sdks\Microsoft.NET.Sdk\codestyle\cs\Microsoft.CodeAnalysis.CodeStyle.dll' references version '4.8.0.0' of the compiler, which is newer than the currently running version '4.7.0.0'.	Accessibility-version	C:\Users\PaulM\Source\Repos\winforms\.dotnet\sdk\8.0.100-preview.7.23376.3\Sdks\Microsoft.NET.Sdk\codestyle\cs\Microsoft.CodeAnalysis.CodeStyle.dll	1	Active
```

_Originally posted by @paul1956 in https://github.com/dotnet/winforms/issues/9807#issuecomment-1707643187_

**Comment by elachlan** [comment]
@lonitra created the issue. Does the team want to remove the package and use the SDK version of the analyzers?

**Comment by Tanya-Solyanik** [comment]
@paul1956 - what version of the VS are you on?

**Comment by elachlan** [comment]
@Tanya-Solyanik do we need VS preview? I get these warnings in VS 2022 17.7.3

![image](https://github.com/dotnet/winforms/assets/2433737/d48bc7a5-a134-4c5f-9304-972538e7c6cc)

**Comment by paul1956** [comment]
> @paul1956 - what version of the VS are you on?

Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.7.3

I used below from PowerShell to start Visual Studio. 
```
.\start-vs.cmd
```
I also have the current preview Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.8.0 Preview 1.0
 but don't know how to start it with the included script as it always starts the production version.

**Comment by merriemcgaw** [comment]
@paul1956 is this solved by launching with the correct developer command prompt?

**Comment by paul1956** [comment]
@merriemcgaw both solutions above work to start the prerelease version of VS. The original issue about sdk warnings is not solved in production release, it is solved in prerelease.
Thanks.
